name: mini_sips
description: Alcohol Tracker
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  cloud_firestore: ^4.13.6
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.15.3
  firebase_core: ^2.24.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  geolocator: ^10.1.0
  modal_bottom_sheet: ^3.0.0-pre
  provider: ^6.1.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
